"""Add Service model

Revision ID: 1057c4014ae7
Revises: c778ded3af34
Create Date: 2025-09-14 11:03:43.782525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1057c4014ae7'
down_revision = 'c778ded3af34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_b2c_lead',
    sa.Column('enquiry_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contact_no', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('enquiry_date', sa.DATE(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=13), nullable=True),
    sa.Column('services', sa.VARCHAR(length=200), nullable=True),
    sa.Column('referred_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('followup1', sa.DATE(), nullable=True),
    sa.Column('followup1_detail', sa.TEXT(), nullable=True),
    sa.Column('followup2', sa.DATE(), nullable=True),
    sa.Column('followup2_detail', sa.TEXT(), nullable=True),
    sa.Column('followup3', sa.DATE(), nullable=True),
    sa.Column('followup3_detail', sa.TEXT(), nullable=True),
    sa.Column('customer_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('updated_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], )
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_name'))

    op.drop_table('service')
    # ### end Alembic commands ###
