"""remove_pdf_link_from_employee

Revision ID: 22ddb772592c
Revises: ec45cf9700e0
Create Date: 2026-01-02 12:13:30.214809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ddb772592c'
down_revision = 'ec45cf9700e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('pdf_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_link', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
