"""Add UserTrackingMixin fields to User model

Revision ID: 240146457c31
Revises: f4afb26c74c9
Create Date: 2025-09-15 00:07:40.520595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240146457c31'
down_revision = 'f4afb26c74c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_updated_by', 'user', ['updated_by'], ['id'])
        batch_op.create_foreign_key('fk_user_created_by', 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
