"""Add customer_id foreign key to booking

Revision ID: 3860bdcddbf5
Revises: 3ac634c059cc
Create Date: 2025-09-06 13:18:02.101329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3860bdcddbf5'
down_revision = '3ac634c059cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_booking_customer_id', ['customer_id'], unique=False)
        batch_op.create_foreign_key('fk_booking_customer_id', 'customer', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_customer_id', type_='foreignkey')
        batch_op.drop_index('idx_booking_customer_id')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
