"""Add employee management models: Attendance, Leave, Task, PerformanceMetric

Revision ID: 571be7a313d6
Revises: 5e2953b00cf6
Create Date: 2025-12-26 16:56:02.478274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571be7a313d6'
down_revision = '5e2953b00cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'LATE', name='attendancestatus'), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('working_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_employee_date', ['employee_id', 'date'], unique=True)
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_employee_id'), ['employee_id'], unique=False)

    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'PATERNITY', 'OTHER', name='leavetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_requested', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_start_date'), ['start_date'], unique=False)

    op.create_table('performance_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('leads_assigned', sa.Integer(), nullable=False),
    sa.Column('leads_converted', sa.Integer(), nullable=False),
    sa.Column('bookings_completed', sa.Integer(), nullable=False),
    sa.Column('revenue_generated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('follow_ups_done', sa.Integer(), nullable=False),
    sa.Column('customer_satisfaction', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('attendance_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_metric', schema=None) as batch_op:
        batch_op.create_index('idx_performance_employee_date', ['employee_id', 'metric_date'], unique=True)
        batch_op.create_index(batch_op.f('ix_performance_metric_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_metric_metric_date'), ['metric_date'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('lead_id', sa.String(length=20), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_assigned_to'), ['assigned_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_due_date'))
        batch_op.drop_index(batch_op.f('ix_task_assigned_to'))

    op.drop_table('task')
    with op.batch_alter_table('performance_metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_metric_metric_date'))
        batch_op.drop_index(batch_op.f('ix_performance_metric_employee_id'))
        batch_op.drop_index('idx_performance_employee_date')

    op.drop_table('performance_metric')
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_start_date'))
        batch_op.drop_index(batch_op.f('ix_leave_end_date'))
        batch_op.drop_index(batch_op.f('ix_leave_employee_id'))

    op.drop_table('leave')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_date'))
        batch_op.drop_index('idx_attendance_employee_date')

    op.drop_table('attendance')
    # ### end Alembic commands ###
