"""add_financial_management_models

Revision ID: 5e2953b00cf6
Revises: 8535196c3995
Create Date: 2025-12-26 13:49:19.680852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2953b00cf6'
down_revision = '8535196c3995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chart_of_account', schema=None) as batch_op:
        batch_op.create_index('idx_chart_of_account_code_type', ['account_code', 'account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_of_account_account_code'), ['account_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_chart_of_account_account_name'), ['account_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_chart_of_account_account_type'), ['account_type'], unique=False)

    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('item_description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index('idx_purchase_date_vendor_status', ['date', 'vendor_name', 'payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_bill_number'), ['bill_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_vendor_name'), ['vendor_name'], unique=False)

    op.create_table('payment_made',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payee_name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('bill_number', sa.String(length=50), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_made', schema=None) as batch_op:
        batch_op.create_index('idx_payment_made_date_payee_category', ['date', 'payee_name', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_made_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_made_payee_name'), ['payee_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_made_reference_number'), ['reference_number'], unique=True)

    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_service', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index('idx_sale_date_customer_status', ['date', 'customer_name', 'payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sale_payment_status'), ['payment_status'], unique=False)

    op.create_table('payment_received',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_received', schema=None) as batch_op:
        batch_op.create_index('idx_payment_received_date_customer', ['date', 'customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_received_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_received_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_received_reference_number'), ['reference_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_received', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_received_reference_number'))
        batch_op.drop_index(batch_op.f('ix_payment_received_date'))
        batch_op.drop_index(batch_op.f('ix_payment_received_customer_name'))
        batch_op.drop_index('idx_payment_received_date_customer')

    op.drop_table('payment_received')
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_payment_status'))
        batch_op.drop_index(batch_op.f('ix_sale_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_sale_date'))
        batch_op.drop_index(batch_op.f('ix_sale_customer_name'))
        batch_op.drop_index('idx_sale_date_customer_status')

    op.drop_table('sale')
    with op.batch_alter_table('payment_made', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_made_reference_number'))
        batch_op.drop_index(batch_op.f('ix_payment_made_payee_name'))
        batch_op.drop_index(batch_op.f('ix_payment_made_date'))
        batch_op.drop_index('idx_payment_made_date_payee_category')

    op.drop_table('payment_made')
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_vendor_name'))
        batch_op.drop_index(batch_op.f('ix_purchase_payment_status'))
        batch_op.drop_index(batch_op.f('ix_purchase_date'))
        batch_op.drop_index(batch_op.f('ix_purchase_bill_number'))
        batch_op.drop_index('idx_purchase_date_vendor_status')

    op.drop_table('purchase')
    with op.batch_alter_table('chart_of_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chart_of_account_account_type'))
        batch_op.drop_index(batch_op.f('ix_chart_of_account_account_name'))
        batch_op.drop_index(batch_op.f('ix_chart_of_account_account_code'))
        batch_op.drop_index('idx_chart_of_account_code_type')

    op.drop_table('chart_of_account')
    # ### end Alembic commands ###
