"""Change B2CLead source field to enum

Revision ID: 62d824b04f30
Revises: 3860bdcddbf5
Create Date: 2025-09-13 23:48:24.207270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62d824b04f30'
down_revision = '3860bdcddbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2c_lead', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('REFERRAL', 'WEBSITE', 'SOCIAL_MEDIA', 'ADVERTISEMENT', 'COLD_CALL', 'WALK_IN', 'OTHER', name='leadsource'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2c_lead', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.Enum('REFERRAL', 'WEBSITE', 'SOCIAL_MEDIA', 'ADVERTISEMENT', 'COLD_CALL', 'WALK_IN', 'OTHER', name='leadsource'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
