"""update_camp_model_remove_payment_referred_by_add_org_name

Revision ID: 6fafa7b1804e
Revises: 9dbc870e742d
Create Date: 2025-12-16 23:19:32.733538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fafa7b1804e'
down_revision = '9dbc870e742d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('org_name', sa.String(length=200), nullable=True))
        batch_op.drop_column('payment')
        batch_op.drop_column('referred_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_by', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.drop_column('org_name')

    # ### end Alembic commands ###
