"""Replace other_id with employee_id in Expense model

Revision ID: 7ba33c266daf
Revises: aa441c33951a
Create Date: 2025-10-07 21:51:22.377966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba33c266daf'
down_revision = 'aa441c33951a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_expense_employee_id', 'employee', ['employee_id'], ['id'])
        batch_op.drop_column('other_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
