"""Remove meeting fields from B2BLead model

Revision ID: 96b22a28206b
Revises: c8784e0dcb3d
Create Date: 2025-09-15 23:44:03.594486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b22a28206b'
down_revision = 'c8784e0dcb3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_lead', schema=None) as batch_op:
        batch_op.drop_index('idx_b2b_lead_org_email_status')
        batch_op.drop_index('ix_b2b_lead_status')
        batch_op.create_index('idx_b2b_lead_org_email', ['organization_name', 'organization_email'], unique=False)
        batch_op.drop_column('meeting1')
        batch_op.drop_column('task_done')
        batch_op.drop_column('meeting2')
        batch_op.drop_column('status')
        batch_op.drop_column('meeting1_notes')
        batch_op.drop_column('notes')
        batch_op.drop_column('meeting1_task_done')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting1_task_done', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('meeting1_notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('meeting2', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('task_done', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('meeting1', sa.DATE(), nullable=True))
        batch_op.drop_index('idx_b2b_lead_org_email')
        batch_op.create_index('ix_b2b_lead_status', ['status'], unique=False)
        batch_op.create_index('idx_b2b_lead_org_email_status', ['organization_name', 'organization_email', 'status'], unique=False)

    # ### end Alembic commands ###
