"""add_camp_model_for_health_camps

Revision ID: 9dbc870e742d
Revises: a77c96e0243e
Create Date: 2025-12-09 15:50:44.785521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbc870e742d'
down_revision = 'a77c96e0243e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.String(length=20), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('camp_date', sa.Date(), nullable=False),
    sa.Column('camp_location', sa.String(length=200), nullable=False),
    sa.Column('referred_by', sa.String(length=100), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('test_done', sa.Boolean(), nullable=False),
    sa.Column('package', sa.String(length=100), nullable=True),
    sa.Column('diagnostic_partner', sa.String(length=100), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.create_index('idx_camp_date_location_patient', ['camp_date', 'camp_location', 'patient_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_camp_camp_date'), ['camp_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_camp_camp_id'), ['camp_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_camp_patient_name'), ['patient_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_camp_phone_no'), ['phone_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_camp_phone_no'))
        batch_op.drop_index(batch_op.f('ix_camp_patient_name'))
        batch_op.drop_index(batch_op.f('ix_camp_camp_id'))
        batch_op.drop_index(batch_op.f('ix_camp_camp_date'))
        batch_op.drop_index('idx_camp_date_location_patient')

    op.drop_table('camp')
    # ### end Alembic commands ###
