"""add_pan_no_to_employee

Revision ID: a29cabdd01ba
Revises: 571be7a313d6
Create Date: 2026-01-02 12:01:43.264773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29cabdd01ba'
down_revision = '571be7a313d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pan_no', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('pan_no')

    # ### end Alembic commands ###
