"""make_channel_partner_created_date_optional

Revision ID: a77c96e0243e
Revises: 7ba33c266daf
Create Date: 2025-12-04 14:27:06.844078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77c96e0243e'
down_revision = '7ba33c266daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_partner', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_partner', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
