"""Add Meeting model for B2B leads

Revision ID: c8784e0dcb3d
Revises: cfc8266bb865
Create Date: 2025-09-15 22:26:42.940371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8784e0dcb3d'
down_revision = 'cfc8266bb865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('b2b_lead_id', sa.Integer(), nullable=False),
    sa.Column('meeting1_date', sa.Date(), nullable=True),
    sa.Column('meeting2_date', sa.Date(), nullable=True),
    sa.Column('meeting1_notes', sa.Text(), nullable=True),
    sa.Column('meeting1_task_done', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('task_done', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['b2b_lead_id'], ['b2b_lead.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting')
    # ### end Alembic commands ###
