"""Remove email fields from B2BLead model

Revision ID: cfc8266bb865
Revises: ec5573ba835b
Create Date: 2025-09-15 22:07:34.779815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc8266bb865'
down_revision = 'ec5573ba835b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_lead', schema=None) as batch_op:
        batch_op.drop_column('email1')
        batch_op.drop_column('email3')
        batch_op.drop_column('email5')
        batch_op.drop_column('email2')
        batch_op.drop_column('email4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email4', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('email2', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('email5', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('email3', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('email1', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
