"""Add charge_type and shift_hours to Booking model

Revision ID: e99123afd97f
Revises: 8589fdfffdb9
Create Date: 2025-10-06 12:07:44.785690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99123afd97f'
down_revision = '8589fdfffdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charge_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('shift_hours', sa.Integer(), nullable=True))
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('shift_hours')
        batch_op.drop_column('charge_type')

    # ### end Alembic commands ###
