"""Change B2CLead source and status to string columns

Revision ID: e9d946acd4f7
Revises: 96b22a28206b
Create Date: 2025-10-02 20:06:25.010712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d946acd4f7'
down_revision = '96b22a28206b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2c_lead', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_b2c_lead_enquiry_id'), ['enquiry_id'], unique=True)

    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.alter_column('lead_type',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('B2C', 'B2B', name='leadtype'),
               existing_nullable=False)
        batch_op.alter_column('outcome',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('CALLED', 'WHATSAPP', 'EMAIL', 'MEETING', 'SCHEDULED', 'NO_RESPONSE', 'OTHER', name='followupoutcome'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_follow_up_follow_up_on'), ['follow_up_on'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_up_follow_up_on'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('outcome',
               existing_type=sa.Enum('CALLED', 'WHATSAPP', 'EMAIL', 'MEETING', 'SCHEDULED', 'NO_RESPONSE', 'OTHER', name='followupoutcome'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
        batch_op.alter_column('lead_type',
               existing_type=sa.Enum('B2C', 'B2B', name='leadtype'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)

    with op.batch_alter_table('b2c_lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_b2c_lead_enquiry_id'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)

    # ### end Alembic commands ###
