"""change_total_experience_to_numeric

Revision ID: ec45cf9700e0
Revises: a29cabdd01ba
Create Date: 2026-01-02 12:07:01.774177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec45cf9700e0'
down_revision = 'a29cabdd01ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('total_experience',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('total_experience',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
