"""Make B2BLead sr_no not nullable and unique

Revision ID: ec5573ba835b
Revises: 240146457c31
Create Date: 2025-09-15 21:48:22.613047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5573ba835b'
down_revision = '240146457c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_lead', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_b2b_lead_sr_no', ['sr_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('b2b_lead', schema=None) as batch_op:
        batch_op.drop_constraint('uq_b2b_lead_sr_no', type_='unique')

    # ### end Alembic commands ###
